services:
    # MySQL
    mysql:
        image: mysql:8.0.39
        container_name: mysql_data_badminton-hub-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: badminton_hub
        ports:
            - '6001:3306'
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql_data_mysql_data_badminton-hub:/var/lib/mysql
        networks:
            - mysql_data_badminton-hub-network

    # Redis
    redis:
        image: redis:latest
        container_name: mysql_data_badminton-hub-redis
        restart: always
        ports:
            - '6002:6379'
        command: ['redis-server', '--appendonly', 'no']
        networks:
            - mysql_data_badminton-hub-network

volumes:
    mysql_data_mysql_data_badminton-hub:

networks:
    mysql_data_badminton-hub-network:
        driver: bridge
